language: ruby
rvm:
  - 2.1.2
env:
  - TEST_DIR=backend
before_script:
  - cd $TEST_DIR && bundle exec rake db:create
script:
  - cd $TEST_DIR && bundle install && bundle exec rake db:migrate && bundle exec rspec

